### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-mercarf#1]
Muy buen trabajo @mercarf!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 285 / 347
- [ ] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by mercarf** [comment]
he actualizado las mejoras, a falta del primer punto:
CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/.`
No entiendo a qué se refiere, mi carpeta stylsheets se tiene que llamar styles?

**Comment by migueldelmazo** [comment]
Hola @mercarf no te preocupes. Esto lo ponemos para que pongáis el css dentro de una carpeta. stylesheets es un nombre perfecto. 

Buen trabajo!!
